services:
  client:
    image: node:12-alpine
    working_dir: /app
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - "${DOCKER_CLIENT_PORT}:${DOCKER_CLIENT_PORT}"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    command: ["sh", "-c", "npm install && npm start"]

  server:
    image: golang:1.24.1-alpine
    working_dir: /app
    env_file:
      - .env
    ports:
      - "${DOCKER_SERVER_PORT}:${DOCKER_SERVER_PORT}"
    volumes:
      - "./server:/app"
    command: ["sh", "-c", "go mod download && go run main.go"]
